#!/usr/bin/env bash
# Install nginx web server and basic setup
sudo apt-get update
sudo apt-get -y install nginx
# Adjust the firewall
sudo ufw enable -y
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx HTTP'
sudo cp /usr/share/nginx/html/index.html /usr/share/nginx/html/backup_index.html
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
sudo service nginx start
