#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file
hfile="holbertonschool"
if [ -e "$hfile" ] || [ -d "$hfile" ]
then
    echo "$hfile file exists"
    if [ ! -s "$hfile" ]
    then
	echo "$hfile file is empty"
    else
	echo "$hfile file is not empty"
    fi
    if [ -f "$hfile" ]
    then
	echo "$hfile file is a regular file"
    fi
else
    echo "$hfile file does not exist"
fi
